version: "3.9"
services:

  Calendar:
    container_name: calendar
    image: "calendarms"
    build: 
      context: Calendar-service
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/calendardb?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mypass00/
    depends_on:
      - Eureka
      - db-mysql

  Course:
    container_name: course
    image: "coursems"
    build:
      context: Course-service
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/coursedb?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mypass00/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - Eureka
      - db-mysql

  User:
    container_name: user
    image: "userms"
    build:
      context: User-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mypass00/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - Eureka
      - db-mysql

  Evaluation:
    container_name: evaluation
    image: "evaluationms"
    build:
      context: Evaluation-service
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - Eureka

#  Chat:
#    container_name: chat
#    image: "chatms"
#    build:
#      context: Chat-serivce
#      dockerfile: Dockerfile
#    ports:
#      - "7174:7174"
#      - "127.0.0.1:5263:5263"
#
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
#      - SPRING_DATA_MONGODB_HOST=db-mongo
#      - SPRING_DATA_MONGODB_PORT=27017
#      - ASPNETCORE_ENVIRONMENT=Production
#    depends_on:
#      - Eureka
#      - db-mongo

  Eureka:
    container_name: eureka
    image: "eureka"
    build:
      context: Discovery-service
      dockerfile: Dockerfile
    hostname: serviceregistry
    ports:
      - "8761:8761"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass00/
    ports:
      - "3307:3306"
    restart: unless-stopped

  db-mongo:
    image: "mongo"
    container_name: db-mongo
    ports:
      - "27016:27017"
    restart: unless-stopped

  Gateway:
    container_name: gateway
    image: "gatewayms"
    build:
      context: Api-gateway
      dockerfile: Dockerfile
    ports:
      - "9020:9020"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    restart: unless-stopped
    depends_on:
      - Eureka
      - keycloak


  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

